#!/bin/bash

function copy_dependencies {
    local file="$1"
    local dir="$2"

    local dependencies=$(ldd "$file" | awk '{if (match($3,"/")){printf("%s\n"),$3}}')

    cp -v "$file" "$dir/"

    for dependency in $dependencies; do
        if [ ! -f "$dir/$(basename $dependency)" ]; then
            copy_dependencies "$dependency" "$dir"
        fi
    done
}

mkdir -p $2
copy_dependencies "$1" "$2"

